export const SEED_COMPANIES = [
  { name: "Google", category: "Tech & AI", location: "Mountain View, CA", website: "https://google.com", logoColor: "#4285F4" },
  { name: "Meta", category: "Tech & AI", location: "Menlo Park, CA", website: "https://meta.com", logoColor: "#0668E1" },
  { name: "Amazon", category: "Tech & AI", location: "Seattle, WA", website: "https://amazon.com", logoColor: "#FF9900" },
  { name: "Apple", category: "Tech & AI", location: "Cupertino, CA", website: "https://apple.com", logoColor: "#555555" },
  { name: "Microsoft", category: "Tech & AI", location: "Redmond, WA", website: "https://microsoft.com", logoColor: "#00A4EF" },
  { name: "Netflix", category: "Tech & AI", location: "Los Gatos, CA", website: "https://netflix.com", logoColor: "#E50914" },
  { name: "NVIDIA", category: "Tech & AI", location: "Santa Clara, CA", website: "https://nvidia.com", logoColor: "#76B900" },
  { name: "OpenAI", category: "Tech & AI", location: "San Francisco, CA", website: "https://openai.com", logoColor: "#000000" },
  { name: "Stripe", category: "Software Services", location: "South San Francisco, CA", website: "https://stripe.com", logoColor: "#635BFF" },
  { name: "Tesla", category: "Engineering & Science", location: "Austin, TX", website: "https://tesla.com", logoColor: "#E31937" },
  { name: "SpaceX", category: "Engineering & Science", location: "Hawthorne, CA", website: "https://spacex.com", logoColor: "#000000" },
  { name: "Airbnb", category: "Software Services", location: "San Francisco, CA", website: "https://airbnb.com", logoColor: "#C00A07" },
  { name: "Uber", category: "Software Services", location: "San Francisco, CA", website: "https://uber.com", logoColor: "#000000" },
  { name: "Shopify", category: "Software Services", location: "Ottawa, Canada", website: "https://shopify.com", logoColor: "#96B24E" },
  { name: "Salesforce", category: "Software Services", location: "San Francisco, CA", website: "https://salesforce.com", logoColor: "#00A0CA" },
  { name: "Adobe", category: "Software Services", location: "San Jose, CA", website: "https://adobe.com", logoColor: "#FF0000" },
  { name: "Citadel", category: "Research Labs", location: "Miami, FL", website: "https://citadel.com", logoColor: "#000000" },
  { name: "Jane Street", category: "Research Labs", location: "New York, NY", website: "https://janestreet.com", logoColor: "#000000" },
  { name: "Two Sigma", category: "Research Labs", location: "New York, NY", website: "https://twosigma.com", logoColor: "#000000" },
  { name: "Goldman Sachs", category: "Research Labs", location: "New York, NY", website: "https://goldmansachs.com", logoColor: "#003B7F" },
  { name: "Systems Ltd", category: "Software Services", location: "Lahore, Pakistan", website: "https://systemsltd.com", logoColor: "#E31B23" },
  { name: "Arbisoft", category: "Software Services", location: "Lahore, Pakistan", website: "https://arbisoft.com", logoColor: "#0054A6" },
  { name: "10Pearls", category: "Software Services", location: "Islamabad, Pakistan", website: "https://10pearls.com", logoColor: "#F7941D" },
  { name: "VentureDive", category: "Software Services", location: "Lahore, Pakistan", website: "https://venturedive.com", logoColor: "#000000" },
  { name: "Netcentric", category: "Software Services", location: "Islamabad, Pakistan", website: "https://netcentric.pk", logoColor: "#00BFFF" },
  { name: "Folio3", category: "Software Services", location: "Lahore, Pakistan", website: "https://folio3.com", logoColor: "#FF6600" },
  { name: "Contour Software", category: "Software Services", location: "Islamabad, Pakistan", website: "https://contoursft.com", logoColor: "#003366" },
  { name: "S&P Global", category: "Research Labs", location: "Islamabad, Pakistan", website: "https://spglobal.com", logoColor: "#E31B23" },
  { name: "Jazz", category: "Tech & AI", location: "Islamabad, Pakistan", website: "https://jazz.com.pk", logoColor: "#FFCC00" },
  { name: "Telenor", category: "Tech & AI", location: "Islamabad, Pakistan", website: "https://telenor.com.pk", logoColor: "#0066CC" },
  { name: "Zong", category: "Tech & AI", location: "Islamabad, Pakistan", website: "https://zong.com.pk", logoColor: "#009933" },
  { name: "Palantir", category: "Tech & AI", location: "Denver, CO", website: "https://palantir.com", logoColor: "#000000" },
  { name: "Snowflake", category: "Software Services", location: la "Bozeman, MT", website: "https://snowflake.com", logoColor: "#29B5E8" },
  { name: "Databricks", category: "Tech & AI", location: "San Francisco, CA", website: "https://databricks.com", logoColor: "#FF3300" },
  { name: "Cloudflare", category: "Software Services", location: "San Francisco, CA", website: "https://cloudflare.com", logoColor: "#F38020" },
  { name: "Samsara", category: "Tech & AI", location: "San Francisco, CA", website: "https://samsara.com", logoColor: "#000000" },
  { name: "Plaid", category: "Software Services", location: "San Francisco, CA", website: "https://plaid.com", logoH Color: "#000000" },
  { name: "DoorDash", category: "Software Services", location: "San Francisco, CA", website: "https://doordash.com", logoColor: "#FF3008" },
  { name: "Instacart", category: "Software Services", location: "San Francisco, CA", website: "https://instacart.com", logoColor: "#43B02A" },
  { name: "Waymo", category: "Tech & AI", location: "Mountain View, CA", website: "https://waymo.com", logoColor: "#000000" },
  { name: "DeepMind", category: "Research Labs", location: "London, UK", website: "https://deepmind.google", logoColor: "#4285F4" },
  { name: "Mistral AI", category: "Tech & AI", location: "Paris, France", website: "https://mistral.ai", logoColor: "#000000" },
  { name: "Anthropic", category: "Tech & AI", location: "San Francisco, CA", website: "https://anthropic.com", logoColor: "#D97757" },
  { name: "Cohere", category: "Tech & AI", location: "Toronto, Canada", website: "https://cohere.com", logoColor: "#000000" },
  { name: "Hugging Face", category: "Tech & AI", location: "New York, NY", website: "https://huggingface.co", logoColor: "#FFD21E" },
  { name: "Robinhood", category: "Software Services", location: la "Menlo Park, CA", website: "https://robinhood.com", logoColor: "#00C7B7" },
  { name: "Coinbase", category: "Software Services", location: la "Remote", website: "https://coinbase.com", logoColor: "#0052FF" },
  { name: "Pinterest", category: "Software Services", location: "San Francisco, CA", website: "https://pinterest.com", logoColor: "#E60023" },
  { name: "Snap", category: "Tech & AI", location: "Santa Monica, CA", website: "https://snapchat.com", logoColor: "#FFFC00" },
  { name: "TikTok", category: "Tech & AI", location: la "Los Angeles, CA", website: "https://tiktok.com", logoColor: "#000000" },
];
